http://localhost:3000

###

POST http://localhost:3000/send-email
Content-Type: application/json

{
    "to" : "anonylatif@gmail.com",
    "subject" : "Greenland Cleaning Service",
    "status" : "Pending",
    "user" : "latifm8360@gmail.com",
    "pass" : "ziez xcek uckf uhyw"
}

###

POST https://sendmail1.vercel.app/send-email
Content-Type: application/json

{
    "to" : "anonylatif@gmail.com",
    "subject" : "Greenland Cleaning Service",
    "status" : "Pending",
    "user" : "latifm8360@gmail.com",
    "pass" : "ziez xcek uckf uhyw",
    "service" : "Cleaning",
    "company" : "Tech"
}

###

POST http://localhost:3000/send-client-email
Content-Type: application/json

{
    "toName": "Abdul",
    "to": "anonylatif@gmail.com",
    "subject": "New Appointment Booked",
    "status": "Pending",
    "user": "latifm8360@gmail.com",
    "pass": "ziez xcek uckf uhyw",
    "employeeName": "Sandra Osei",
    "position": "HR"
}